# kubectl apply -f k8s.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: siop
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: siop-ingress
  namespace: siop
spec:
  rules:
  - host: demo-portals.smarthealth.cards
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: demo-portals
            port:
              number: 80
  tls:
  - hosts:
    - demo-portals.smarthealth.cards
    secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: siop
  name: demo-portals
spec:
  selector:
    app: demo-portals
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: siop
  name: demo-portals
  labels:
    app: demo-portals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-portals
  template:
    metadata:
      labels:
        app: demo-portals
    spec:
      volumes:
      containers:
      - name: demo-portals
        image: ghcr.io/smart-on-fhir/health-cards-tests:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_BASE
          value: "https://demo-portals.smarthealth.cards/"
