name: Deploy Server to k8s
on:
  workflow_dispatch:
  push:
    branches:
    - master
permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  build:
    environment: k8deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and rollout to CI
      working-directory: demo-portals
      run: |
        docker build . \
          -t ghcr.io/smart-on-fhir/health-cards-tests:$GITHUB_SHA \
          -t ghcr.io/smart-on-fhir/health-cards-tests:latest
        docker push ghcr.io/smart-on-fhir/health-cards-tests
        # kubectl -n siop rollout restart deployment/demo-portals
