name: Deploy Health Wallet Demo master branch to ci
# Basics from https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/github-actions
on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    paths:
      - "demo-portals/**"

jobs:
  build-demo-portals:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ fromJSON(secrets.AKS_2023).containerRegistry }}
        username: ${{ fromJSON(secrets.AKS_2023).clientId }}
        password: ${{ fromJSON(secrets.AKS_2023).clientSecret }}
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AKS_2023 }}
    - uses: azure/aks-set-context@v3
      with:
        cluster-name: ${{ fromJSON(secrets.AKS_2023).clusterName }}
        resource-group: ${{ fromJSON(secrets.AKS_2023).resourceGroup }}
        admin: 'true'
    - name: Build and rollout to CI
      working-directory: demo-portals
      run: |
        docker build . \
          -t ${{ fromJSON(secrets.AKS_2023).containerRegistry }}/demo-portals:$GITHUB_SHA \
          -t ${{ fromJSON(secrets.AKS_2023).containerRegistry }}/demo-portals:latest
        docker push ${{ fromJSON(secrets.AKS_2023).containerRegistry }}/demo-portals
        kubectl -n siop rollout restart deployment/demo-portals
